In [797]:
import numpy as np


In [798]:
a = np.array([1,2,3])
b = np.array([(1.5,2,3),(4,5,6)], dtype=float)
c = np.array([[(1.5,2,3),(4,5,6)],[(3,2,1),(4,5,6)]],dtype=float)
c

array([[[1.5, 2. , 3. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 1. ],
        [4. , 5. , 6. ]]])

In [799]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [800]:
np.ones((2,3,4),dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [801]:
d = np.arange(10,25,5)
d

array([10, 15, 20])

In [802]:
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [803]:
e = np.full((2,2),7)
e

array([[7, 7],
       [7, 7]])

In [878]:
f = np.eye(2)
f

array([[1., 0.],
       [0., 1.]])

In [805]:
np.random.random((2,2))

array([[0.65643603, 0.3082942 ],
       [0.9658099 , 0.81392412]])

In [806]:
np.empty((3,2))

array([[1.5, 2. ],
       [3. , 4. ],
       [5. , 6. ]])

In [807]:
#np.save('my_array',a)
#np.savez('array.npz',a,b)
#np.load('my_array.npy')

In [808]:
#np.loadtxt('myfile.txt')
#np.genfromtxt('my_file.csv',delimiter=',')
#np.savetxt('myarray.txt',a,delimiter=" ")

In [809]:
np.info(np.ndarray)

 ndarray()

ndarray(shape, dtype=float, buffer=None, offset=0,
        strides=None, order=None)

An array object represents a multidimensional, homogeneous array
of fixed-size items.  An associated data-type object describes the
format of each element in the array (its byte-order, how many bytes it
occupies in memory, whether it is an integer, a floating point number,
or something else, etc.)

Arrays should be constructed using `array`, `zeros` or `empty` (refer
to the See Also section below).  The parameters given here refer to
a low-level method (`ndarray(...)`) for instantiating an array.

For more information, refer to the `numpy` module and examine the
methods and attributes of an array.

Parameters
----------
(for the __new__ method; see Notes below)

shape : tuple of ints
    Shape of created array.
dtype : data-type, optional
    Any object that can be interpreted as a numpy data type.
buffer : object exposing buffer interface, optional
    Used to fill the array with data.
of

In [810]:
a.shape

(3,)

In [811]:
len(a)

3

In [796]:
b.ndim

2

In [812]:
e.size

4

In [813]:
b.dtype

dtype('float64')

In [814]:
b.dtype.name

'float64'

In [867]:
b.astype(int)

array([[1, 2, 3],
       [4, 5, 6]])

In [816]:
#np.int64
#np.float32
#complex
#bool
#object
#np.string_
#np.unicode_

In [868]:
np.exp(b)

array([[  4.48168907,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [871]:
g = a - b
g
np.subtract(a,b)

array([[-0.5,  0. ,  0. ],
       [-3. , -3. , -3. ]])

In [872]:
#b + a
np.add(b,a)

array([[2.5, 4. , 6. ],
       [5. , 7. , 9. ]])

In [873]:
#a / b
np.divide(a,b)

array([[0.66666667, 1.        , 1.        ],
       [0.25      , 0.4       , 0.5       ]])

In [874]:
#a * b
np.multiply(a,b)

array([[ 1.5,  4. ,  9. ],
       [ 4. , 10. , 18. ]])

In [875]:
np.sqrt(b)


array([[1.22474487, 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [823]:
np.sin(a)


array([0.84147098, 0.90929743, 0.14112001])

In [876]:
np.cos(b)


array([[ 0.0707372 , -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029]])

In [825]:
np.log(a)


array([0.        , 0.69314718, 1.09861229])

In [879]:
e.dot(f)

array([[7., 7.],
       [7., 7.]])

In [827]:

np.array_equal(a,b)

False

In [880]:
a.sum()


6

In [881]:
a.min()


1

In [882]:
b.max(axis=0)


array([4., 5., 6.])

In [831]:
b.cumsum(axis=0)


array([[1.5, 2. , 3. ],
       [5.5, 7. , 9. ]])

In [832]:
a.mean()


2.0

In [833]:
np.median(b)


3.5

In [834]:
np.corrcoef(a)


1.0

In [883]:
np.std(b)

1.5920810978785667

In [884]:
h = a.view()


In [885]:
np.copy(a)


array([1, 2, 3])

In [887]:
h = a.copy()
h

array([1, 2, 3])

In [888]:
a.sort()

In [889]:
c.sort(axis=0)
c

array([[[1.5, 2. , 1. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 3. ],
        [4. , 5. , 6. ]]])

In [890]:
a[2]

3

In [891]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [892]:
b[1,2]

6.0

In [893]:
a[0:3]


array([1, 2, 3])

In [894]:
b[0:2,1]


array([2., 5.])

In [895]:
b[:1]


array([[1.5, 2. , 3. ]])

In [896]:
c

array([[[1.5, 2. , 1. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 3. ],
        [4. , 5. , 6. ]]])

In [898]:
c[1,0,...]


array([3., 2., 3.])

In [847]:
a[::-1]


array([3, 2, 1])

In [848]:
a[a<2]


array([1])

In [901]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [899]:
b[[1,0,1,0],[0,1,2,0]]


array([4. , 2. , 6. , 1.5])

In [900]:
b[[1,0,1,0]][:,[0,1,2,0]]

array([[4. , 5. , 6. , 4. ],
       [1.5, 2. , 3. , 1.5],
       [4. , 5. , 6. , 4. ],
       [1.5, 2. , 3. , 1.5]])

In [902]:
i = np.transpose(b)
i


array([[1.5, 4. ],
       [2. , 5. ],
       [3. , 6. ]])

In [852]:
i.T

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [853]:
b.ravel()


array([1.5, 2. , 3. , 4. , 5. , 6. ])

In [904]:
g

array([[-0.5,  0. ,  0. ],
       [-3. , -3. , -3. ]])

In [903]:
g.reshape(3,-2)

array([[-0.5,  0. ],
       [ 0. , -3. ],
       [-3. , -3. ]])

In [911]:
h.resize((2,6))


ValueError: cannot resize an array that references or is referenced
by another array in this way.
Use the np.resize function or refcheck=False

In [906]:
np.append(h,a)


array([1, 2, 3, 1, 2, 3])

In [907]:
np.insert(a,1,5)


array([1, 5, 2, 3])

In [909]:
np.delete(a,[1])

array([1, 3])

In [912]:
np.concatenate((a,d),axis=0)



array([ 1,  2,  3, 10, 15, 20])

In [913]:
np.vstack((a,b))


array([[1. , 2. , 3. ],
       [1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [914]:
np.r_[e,f]


array([[7., 7.],
       [7., 7.],
       [1., 0.],
       [0., 1.]])

In [915]:
np.hstack((e,f))


array([[7., 7., 1., 0.],
       [7., 7., 0., 1.]])

In [916]:
np.column_stack((a,d))


array([[ 1, 10],
       [ 2, 15],
       [ 3, 20]])

In [917]:
np.c_[a,d]

array([[ 1, 10],
       [ 2, 15],
       [ 3, 20]])

In [921]:
np.hsplit(a,3)


[array([1]), array([2]), array([3])]

In [919]:
np.vsplit(c,2)

[array([[[1.5, 2. , 1. ],
         [4. , 5. , 6. ]]]),
 array([[[3., 2., 3.],
         [4., 5., 6.]]])]