In [888]:
#create numpy array (1d,2d,3d)
#change one and mulitple values by choice by dimension(rows and columns in separate subarrays)
#change multiple values by condition by dimension(rows and columns in separate subarrays)
#ex. if values are between, change with specific values
#utilize loops/functions
#multiple conditions
#fromfunction

In [889]:
import numpy as np


In [890]:
a = np.array([2, 3, 4])
a

array([2, 3, 4])

In [891]:
b = np.array([(1.5, 2, 3), (4, 5, 6)])
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [892]:
c = np.arange(24).reshape(2, 3, 4)  # 3d array
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [893]:
a[0] = 23
a

array([23,  3,  4])

In [894]:
a[[1,2]] = 43
a

array([23, 43, 43])

In [895]:
b[1,2] = 43
b

array([[ 1.5,  2. ,  3. ],
       [ 4. ,  5. , 43. ]])

In [896]:
b[0,1:3] = 23
b

array([[ 1.5, 23. , 23. ],
       [ 4. ,  5. , 43. ]])

In [897]:
c[:,1,0] = 64
c

array([[[ 0,  1,  2,  3],
        [64,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [64, 17, 18, 19],
        [20, 21, 22, 23]]])

In [898]:
c[1,:,1] = 88
c

array([[[ 0,  1,  2,  3],
        [64,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 88, 14, 15],
        [64, 88, 18, 19],
        [20, 88, 22, 23]]])

In [899]:
c[0,2,:] = 99
c

array([[[ 0,  1,  2,  3],
        [64,  5,  6,  7],
        [99, 99, 99, 99]],

       [[12, 88, 14, 15],
        [64, 88, 18, 19],
        [20, 88, 22, 23]]])

In [900]:
a

array([23, 43, 43])

In [901]:
if a[1]>22:
    a[1] = 20
a

array([23, 20, 43])

In [902]:
for i in range(len(a)):
    if a[i]>42 and a[i]==43:
        a[i]=28
a

array([23, 20, 28])

In [903]:
if len(a) == 3:
    a = a.reshape(3,1)
a

array([[23],
       [20],
       [28]])

In [904]:
a = a.reshape(1,3)
a

array([[23, 20, 28]])

In [905]:
b

array([[ 1.5, 23. , 23. ],
       [ 4. ,  5. , 43. ]])

In [906]:
arb = b[0,:]>22
for i in range(len(arb)):
    if arb[i]:
        b[0,i] = 11
b

array([[ 1.5, 11. , 11. ],
       [ 4. ,  5. , 43. ]])

In [907]:
arb = b[:,2]>9
for i in range(len(arb)):
    if arb[i]:
        b[i,2] = 15
b

array([[ 1.5, 11. , 15. ],
       [ 4. ,  5. , 15. ]])

In [908]:
c

array([[[ 0,  1,  2,  3],
        [64,  5,  6,  7],
        [99, 99, 99, 99]],

       [[12, 88, 14, 15],
        [64, 88, 18, 19],
        [20, 88, 22, 23]]])

In [909]:
arc = c[0,:]>2
for i in range(arc.shape[0]):
    for j in range(arc.shape[1]):
        if arc[i,j]:
            c[0,i,j] = 10
c

array([[[ 0,  1,  2, 10],
        [10, 10, 10, 10],
        [10, 10, 10, 10]],

       [[12, 88, 14, 15],
        [64, 88, 18, 19],
        [20, 88, 22, 23]]])

In [910]:
arc = c[:,:,2]<20
arc1 = c[:,:,2]>5
cs = c[:,:,2].sum()
for i in range(arc.shape[0]):
    for j in range(arc.shape[1]):
        if arc[i,j] and arc1[i,j]:
            c[i,j,2] = cs
c


array([[[ 0,  1,  2, 10],
        [10, 10, 76, 10],
        [10, 10, 76, 10]],

       [[12, 88, 76, 15],
        [64, 88, 76, 19],
        [20, 88, 22, 23]]])

In [911]:
arc = c[0,0,:]<5
arc1 = c[1,1,:]<65
for i in range(c.shape[2]):
    if arc1[i]:
        c[1,1,i] = c[1,1,:].min()
    if arc[i]:
        c[0,0,i] = c[0,0,:].min()
c

array([[[ 0,  0,  0, 10],
        [10, 10, 76, 10],
        [10, 10, 76, 10]],

       [[12, 88, 76, 15],
        [19, 88, 76, 19],
        [20, 88, 22, 23]]])

In [912]:
np.fromfunction(lambda i, j: i == j, (3, 3), dtype=int)

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [913]:
np.fromfunction(lambda i, j: i + j, (6, 6), dtype=int)

array([[ 0,  1,  2,  3,  4,  5],
       [ 1,  2,  3,  4,  5,  6],
       [ 2,  3,  4,  5,  6,  7],
       [ 3,  4,  5,  6,  7,  8],
       [ 4,  5,  6,  7,  8,  9],
       [ 5,  6,  7,  8,  9, 10]])

In [914]:
np.fromfunction(lambda i,j,k: 100*i+10*j+k, (3,3,3), dtype=int)


array([[[  0,   1,   2],
        [ 10,  11,  12],
        [ 20,  21,  22]],

       [[100, 101, 102],
        [110, 111, 112],
        [120, 121, 122]],

       [[200, 201, 202],
        [210, 211, 212],
        [220, 221, 222]]])

In [916]:
def f(i,j,k):
    return 100*i+10*j+k

s = np.fromfunction(f, (3,3,3), dtype=int)
s

array([[[  0,   1,   2],
        [ 10,  11,  12],
        [ 20,  21,  22]],

       [[100, 101, 102],
        [110, 111, 112],
        [120, 121, 122]],

       [[200, 201, 202],
        [210, 211, 212],
        [220, 221, 222]]])