In [ ]:
import numpy as np

a = np.arange(15).reshape(3, 5)

a

a.shape

a.ndim

a.dtype.name

a.itemsize

a.size

type(a)

b = np.array([6, 7, 8])

b

type(b)

In [ ]:
#array creation

a = np.array([2, 3, 4])

a

a.dtype

b = np.array([1.2, 3.5, 5.1])

b.dtype

In [ ]:
b = np.array([(1.5, 2, 3), (4, 5, 6)])

b

In [ ]:
c = np.array([[1, 2], [3, 4]], dtype=complex)

c

In [ ]:
np.zeros((3, 4))

In [ ]:
np.ones((2, 3, 4), dtype=np.int16)

In [ ]:
np.empty((2, 3)) 

In [ ]:
np.arange(10, 30, 5)

In [ ]:
np.arange(0, 2, 0.3) 

In [ ]:
from numpy import pi

np.linspace(0, 2, 9)                   # 9 numbers from 0 to 2

x = np.linspace(0, 2 * pi, 100)        # useful to evaluate function at lots of points

f = np.sin(x)

In [ ]:
a = np.arange(6)                    # 1d array

print(a)

In [ ]:
b = np.arange(12).reshape(4, 3)     # 2d array

print(b)

In [ ]:
c = np.arange(24).reshape(2, 3, 4)  # 3d array

print(c)

In [ ]:
print(np.arange(10000))

In [ ]:
print(np.arange(10000).reshape(100, 100))

In [ ]:
a = np.array([20, 30, 40, 50])

b = np.arange(4)

b
array([0, 1, 2, 3])

c = a - b

c
array([20, 29, 38, 47])

b**2
array([0, 1, 4, 9])

10 * np.sin(a)
array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

a < 35
array([ True,  True, False, False])

In [ ]:
A = np.array([[1, 1],

              [0, 1]])

B = np.array([[2, 0],

              [3, 4]])

A * B     # elementwise product
array([[2, 0],
       [0, 4]])

A @ B     # matrix product
array([[5, 4],
       [3, 4]])

A.dot(B)  # another matrix product
array([[5, 4],
       [3, 4]])


In [ ]:
rg = np.random.default_rng(1)  # create instance of default random number generator

a = np.ones((2, 3), dtype=int)

b = rg.random((2, 3))

a *= 3

a
array([[3, 3, 3],
       [3, 3, 3]])

b += a

b
array([[3.51182162, 3.9504637 , 3.14415961],
       [3.94864945, 3.31183145, 3.42332645]])

a += b  # b is not automatically converted to integer t

In [ ]:
a = np.ones(3, dtype=np.int32)

b = np.linspace(0, pi, 3)

b.dtype.name
'float64'

c = a + b

c
array([1.        , 2.57079633, 4.14159265])

c.dtype.name
'float64'

d = np.exp(c * 1j)

d
array([ 0.54030231+0.84147098j, -0.84147098+0.54030231j,
       -0.54030231-0.84147098j])

d.dtype.name
'complex128'

In [ ]:
a = rg.random((2, 3))

a
array([[0.82770259, 0.40919914, 0.54959369],
       [0.02755911, 0.75351311, 0.53814331]])

a.sum()
3.1057109529998157

a.min()
0.027559113243068367

a.max()
0.8277025938204418

In [ ]:
b = np.arange(12).reshape(3, 4)

b
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])
>>>

b.sum(axis=0)     # sum of each column
array([12, 15, 18, 21])
>>>

b.min(axis=1)     # min of each row
array([0, 4, 8])
>>>

b.cumsum(axis=1)  # cumulative sum along each row
array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

In [ ]:
B = np.arange(3)

B
array([0, 1, 2])

np.exp(B)
array([1.        , 2.71828183, 7.3890561 ])

np.sqrt(B)
array([0.        , 1.        , 1.41421356])

C = np.array([2., -1., 4.])

np.add(B, C)
array([2., 0., 6.])

In [ ]:
a = np.arange(10)**3

a
array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

a[2]
8

a[2:5]
array([ 8, 27, 64])

# equivalent to a[0:6:2] = 1000;

# from start to position 6, exclusive, set every 2nd element to 1000

a[:6:2] = 1000

a
array([1000,    1, 1000,   27, 1000,  125,  216,  343,  512,  729])

a[::-1]  # reversed a
array([ 729,  512,  343,  216,  125, 1000,   27, 1000,    1, 1000])

for i in a:

    print(i**(1 / 3.))


In [ ]:
def f(x, y):

    return 10 * x + y


b = np.fromfunction(f, (5, 4), dtype=int)

b
array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

b[2, 3]
23

b[0:5, 1]  # each row in the second column of b
array([ 1, 11, 21, 31, 41])

b[:, 1]    # equivalent to the previous example
array([ 1, 11, 21, 31, 41])

b[1:3, :]  # each column in the second and third row of b
array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

In [ ]:
b[-1]   # the last row. Equivalent to b[-1, :]
array([40, 41, 42, 43])

In [ ]:
c = np.array([[[  0,  1,  2],  # a 3D array (two stacked 2D arrays)

               [ 10, 12, 13]],

              [[100, 101, 102],

               [110, 112, 113]]])

c.shape
(2, 2, 3)

c[1, ...]  # same as c[1, :, :] or c[1]
array([[100, 101, 102],
       [110, 112, 113]])

c[..., 2]  # same as c[:, :, 2]
array([[  2,  13],
       [102, 113]])

In [ ]:
for row in b:

    print(row)

In [ ]:
for element in b.flat:

    print(element)

In [ ]:
a = np.floor(10 * rg.random((3, 4)))

a
array([[3., 7., 3., 4.],
       [1., 4., 2., 2.],
       [7., 2., 4., 9.]])

a.shape
(3, 4)


In [ ]:
a.ravel()  # returns the array, flattened
array([3., 7., 3., 4., 1., 4., 2., 2., 7., 2., 4., 9.])

a.reshape(6, 2)  # returns the array with a modified shape
array([[3., 7.],
       [3., 4.],
       [1., 4.],
       [2., 2.],
       [7., 2.],
       [4., 9.]])

a.T  # returns the array, transposed
array([[3., 1., 7.],
       [7., 4., 2.],
       [3., 2., 4.],
       [4., 2., 9.]])

a.T.shape
(4, 3)

a.shape
(3, 4)



In [ ]:
a
array([[3., 7., 3., 4.],
       [1., 4., 2., 2.],
       [7., 2., 4., 9.]])

a.resize((2, 6))

a
array([[3., 7., 3., 4., 1., 4.],
       [2., 2., 7., 2., 4., 9.]]

In [ ]:
a.reshape(3, -1)
array([[3., 7., 3., 4.],
       [1., 4., 2., 2.],
       [7., 2., 4., 9.]])

In [ ]:
a = np.floor(10 * rg.random((2, 2)))

a
array([[9., 7.],
       [5., 2.]])

b = np.floor(10 * rg.random((2, 2)))

b
array([[1., 9.],
       [5., 1.]])

np.vstack((a, b))
array([[9., 7.],
       [5., 2.],
       [1., 9.],
       [5., 1.]])

np.hstack((a, b))
array([[9., 7., 1., 9.],
       [5., 2., 5., 1.]])

In [ ]:
from numpy import newaxis

np.column_stack((a, b))  # with 2D arrays
array([[9., 7., 1., 9.],
       [5., 2., 5., 1.]])

a = np.array([4., 2.])

b = np.array([3., 8.])

np.column_stack((a, b))  # returns a 2D array
array([[4., 3.],
       [2., 8.]])

np.hstack((a, b))        # the result is different
array([4., 2., 3., 8.])

a[:, newaxis]  # view `a` as a 2D column vector
array([[4.],
       [2.]])

np.column_stack((a[:, newaxis], b[:, newaxis]))
array([[4., 3.],
       [2., 8.]])

np.hstack((a[:, newaxis], b[:, newaxis]))  # the result is the same
array([[4., 3.],
       [2., 8.]])

In [ ]:
np.column_stack is np.hstack
False

np.row_stack is np.vstack
True

In [ ]:
np.r_[1:4, 0, 4]
array([1, 2, 3, 0, 4])

In [ ]:
a = np.floor(10 * rg.random((2, 12)))

a
array([[6., 7., 6., 9., 0., 5., 4., 0., 6., 8., 5., 2.],
       [8., 5., 5., 7., 1., 8., 6., 7., 1., 8., 1., 0.]])

# Split `a` into 3

np.hsplit(a, 3)
[array([[6., 7., 6., 9.],
       [8., 5., 5., 7.]]), array([[0., 5., 4., 0.],
       [1., 8., 6., 7.]]), array([[6., 8., 5., 2.],
       [1., 8., 1., 0.]])]

# Split `a` after the third and the fourth column

np.hsplit(a, (3, 4))
[array([[6., 7., 6.],
       [8., 5., 5.]]), array([[9.],
       [7.]]), array([[0., 5., 4., 0., 6., 8., 5., 2.],
       [1., 8., 6., 7., 1., 8., 1., 0.]])]

In [ ]:
a = np.array([[ 0,  1,  2,  3],

              [ 4,  5,  6,  7],

              [ 8,  9, 10, 11]])

b = a            # no new object is created

b is a           # a and b are two names for the same ndarray object
True


In [ ]:
c = a.view()

c is a
False

c.base is a            # c is a view of the data owned by a
True

c.flags.owndata
False
>>>

c = c.reshape((2, 6))  # a's shape doesn't change

a.shape
(3, 4)

c[0, 4] = 1234         # a's data changes

a
array([[   0,    1,    2,    3],
       [1234,    5,    6,    7],
       [   8,    9,   10,   11]])

In [ ]:
s = a[:, 1:3]

s[:] = 10  # s[:] is a view of s. Note the difference between s = 10 and s[:] = 10

a
array([[   0,   10,   10,    3],
       [1234,   10,   10,    7],
       [   8,   10,   10,   11]])

In [ ]:
d = a.copy()  # a new array object with new data is created

d is a
False

d.base is a  # d doesn't share anything with a
False

d[0, 0] = 9999

a
array([[   0,   10,   10,    3],
       [1234,   10,   10,    7],
       [   8,   10,   10,   11]])


In [ ]:
a = np.arange(int(1e8))

b = a[:100].copy()

del a  # the memory of ``a`` can be released.


In [ ]:
a = np.arange(12)**2  # the first 12 square numbers

i = np.array([1, 1, 3, 8, 5])  # an array of indices

a[i]  # the elements of `a` at the positions `i`
array([ 1,  1,  9, 64, 25])
>>>

j = np.array([[3, 4], [9, 7]])  # a bidimensional array of indices

a[j]  # the same shape as `j`
array([[ 9, 16],
       [81, 49]])

In [ ]:
palette = np.array([[0, 0, 0],         # black

                    [255, 0, 0],       # red

                    [0, 255, 0],       # green

                    [0, 0, 255],       # blue

                    [255, 255, 255]])  # white

image = np.array([[0, 1, 2, 0],  # each value corresponds to a color in the palette

                  [0, 3, 4, 0]])

palette[image]  # the (2, 4, 3) color image
array([[[  0,   0,   0],
        [255,   0,   0],
        [  0, 255,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0, 255],
        [255, 255, 255],
        [  0,   0,   0]]])

In [ ]:
a = np.arange(12).reshape(3, 4)

a
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

i = np.array([[0, 1],  # indices for the first dim of `a`

              [1, 2]])

j = np.array([[2, 1],  # indices for the second dim

              [3, 3]])
>>>

a[i, j]  # i and j must have equal shape
array([[ 2,  5],
       [ 7, 11]])
>>>

a[i, 2]
array([[ 2,  6],
       [ 6, 10]])
>>>

a[:, j]
array([[[ 2,  1],
        [ 3,  3]],

       [[ 6,  5],
        [ 7,  7]],

       [[10,  9],
        [11, 11]]])


In [ ]:
l = (i, j)

# equivalent to a[i, j]

a[l]
array([[ 2,  5],
       [ 7, 11]])

In [ ]:
s = np.array([i, j])

# not what we want

a[s]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IndexError: index 3 is out of bounds for axis 0 with size 3

# same as `a[i, j]`

a[tuple(s)]
array([[ 2,  5],
       [ 7, 11]])

In [ ]:
time = np.linspace(20, 145, 5)  # time scale

data = np.sin(np.arange(20)).reshape(5, 4)  # 4 time-dependent series

time
array([ 20.  ,  51.25,  82.5 , 113.75, 145.  ])

data
array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849, -0.54402111, -0.99999021],
       [-0.53657292,  0.42016704,  0.99060736,  0.65028784],
       [-0.28790332, -0.96139749, -0.75098725,  0.14987721]])

# index of the maxima for each series

ind = data.argmax(axis=0)

ind
array([2, 0, 3, 1])

# times corresponding to the maxima

time_max = time[ind]
>>>

data_max = data[ind, range(data.shape[1])]  # => data[ind[0], 0], data[ind[1], 1]...

time_max
array([ 82.5 ,  20.  , 113.75,  51.25])

data_max
array([0.98935825, 0.84147098, 0.99060736, 0.6569866 ])

np.all(data_max == data.max(axis=0))
True

In [ ]:
a = np.arange(5)

a
array([0, 1, 2, 3, 4])

a[[1, 3, 4]] = 0

a
array([0, 0, 2, 0, 0])

In [ ]:
a = np.arange(5)

a[[0, 0, 2]] = [1, 2, 3]

a
array([2, 1, 3, 3, 4])


In [ ]:
a = np.arange(5)

a[[0, 0, 2]] += 1

a
array([1, 1, 3, 3, 4])

In [ ]:
a = np.arange(12).reshape(3, 4)

b = a > 4

b  # `b` is a boolean with `a`'s shape
array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

a[b]  # 1d array with the selected elements
array([ 5,  6,  7,  8,  9, 10, 11])


In [ ]:
a[b] = 0  # All elements of `a` higher than 4 become 0

a
array([[0, 1, 2, 3],
       [4, 0, 0, 0],
       [0, 0, 0, 0]])

In [ ]:
import numpy as np

import matplotlib.pyplot as plt

def mandelbrot(h, w, maxit=20, r=2):

    """Returns an image of the Mandelbrot fractal of size (h,w)."""

    x = np.linspace(-2.5, 1.5, 4*h+1)

    y = np.linspace(-1.5, 1.5, 3*w+1)

    A, B = np.meshgrid(x, y)

    C = A + B*1j

    z = np.zeros_like(C)

    divtime = maxit + np.zeros(z.shape, dtype=int)


    for i in range(maxit):

        z = z**2 + C

        diverge = abs(z) > r                    # who is diverging

        div_now = diverge & (divtime == maxit)  # who is diverging now

        divtime[div_now] = i                    # note when

        z[diverge] = r                          # avoid diverging too much


    return divtime

plt.clf()

plt.imshow(mandelbrot(400, 400))

In [ ]:
a = np.arange(12).reshape(3, 4)

b1 = np.array([False, True, True])         # first dim selection

b2 = np.array([True, False, True, False])  # second dim selection
>>>

a[b1, :]                                   # selecting rows
array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])
>>>

a[b1]                                      # same thing
array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])
>>>

a[:, b2]                                   # selecting columns
array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])
>>>

a[b1, b2]                                  # a weird thing to do
array([ 4, 10])

In [ ]:
a = np.array([2, 3, 4, 5])

b = np.array([8, 5, 4])

c = np.array([5, 4, 6, 8, 3])

ax, bx, cx = np.ix_(a, b, c)

ax
array([[[2]],

       [[3]],

       [[4]],

       [[5]]])

bx
array([[[8],
        [5],
        [4]]])

cx
array([[[5, 4, 6, 8, 3]]])

ax.shape, bx.shape, cx.shape
((4, 1, 1), (1, 3, 1), (1, 1, 5))

result = ax + bx * cx

result
array([[[42, 34, 50, 66, 26],
        [27, 22, 32, 42, 17],
        [22, 18, 26, 34, 14]],

       [[43, 35, 51, 67, 27],
        [28, 23, 33, 43, 18],
        [23, 19, 27, 35, 15]],

       [[44, 36, 52, 68, 28],
        [29, 24, 34, 44, 19],
        [24, 20, 28, 36, 16]],

       [[45, 37, 53, 69, 29],
        [30, 25, 35, 45, 20],
        [25, 21, 29, 37, 17]]])

result[3, 2, 4]
17

a[3] + b[2] * c[4]
17

In [ ]:
def ufunc_reduce(ufct, *vectors):

   vs = np.ix_(*vectors)

   r = ufct.identity

   for v in vs:

       r = ufct(r, v)

   return r

In [ ]:
ufunc_reduce(np.add, a, b, c)
array([[[15, 14, 16, 18, 13],
        [12, 11, 13, 15, 10],
        [11, 10, 12, 14,  9]],

       [[16, 15, 17, 19, 14],
        [13, 12, 14, 16, 11],
        [12, 11, 13, 15, 10]],

       [[17, 16, 18, 20, 15],
        [14, 13, 15, 17, 12],
        [13, 12, 14, 16, 11]],

       [[18, 17, 19, 21, 16],
        [15, 14, 16, 18, 13],
        [14, 13, 15, 17, 12]]])


In [ ]:
a = np.arange(30)

b = a.reshape((2, -1, 3))  # -1 means "whatever is needed"

b.shape
(2, 5, 3)

b
array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]]])


In [ ]:
x = np.arange(0, 10, 2)

y = np.arange(5)

m = np.vstack([x, y])

m
array([[0, 2, 4, 6, 8],
       [0, 1, 2, 3, 4]])

xy = np.hstack([x, y])

xy
array([0, 2, 4, 6, 8, 0, 1, 2, 3, 4])


In [ ]:
import numpy as np

rg = np.random.default_rng(1)

import matplotlib.pyplot as plt

# Build a vector of 10000 normal deviates with variance 0.5^2 and mean 2

mu, sigma = 2, 0.5

v = rg.normal(mu, sigma, 10000)

# Plot a normalized histogram with 50 bins

plt.hist(v, bins=50, density=True)       # matplotlib version (plot)
(array...)

# Compute the histogram with numpy and then plot it

(n, bins) = np.histogram(v, bins=50, density=True)  # NumPy version (no plot)

plt.plot(.5 * (bins[1:] + bins[:-1]), n) 
