In [720]:
from sklearn import datasets,preprocessing
#import datasets and preprocessing library
from sklearn.model_selection import train_test_split
#import test/train splititng
from sklearn.metrics import accuracy_score
#import accuracy score
import numpy as np

In [721]:
from sklearn import neighbors
iris = datasets.load_iris()
#load iris dataset
X, y = iris.data[:,:2], iris.target
X_train, X_test, y_train, y_test = train_test_split(X,y,random_state=33)
#split into test/train
scaler = preprocessing.StandardScaler().fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)
#scale feature data
knn = neighbors.KNeighborsClassifier(n_neighbors=5)
#def neighbors model
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)
#fit, predict and grade model accuracy
accuracy_score(y_test, y_pred)

0.631578947368421

In [722]:
import numpy as np
#def feature and target vars
X = np.random.random((10,5))
y = np.array(['M','M','F','F','M','F','M','M','F','F','F'])
X[X<0.7] = 0

In [723]:
from sklearn.preprocessing import StandardScaler
#scale feature vars with standardscaler
scaler = StandardScaler().fit(X_train)
standardized_X = scaler.transform(X_train)
standardized_X_test = scaler.transform(X_test)
standardized_X

array([[-0.91090798, -1.59775374],
       [-1.0271058 ,  0.08448757],
       [ 0.59966379, -1.59775374],
       [ 0.01867465, -0.96691325],
       [ 0.48346596, -0.33607276],
       [-1.25950146,  0.29476773],
       [-1.37569929,  0.71532806],
       [-0.79471015, -1.17719341],
       [-1.14330363,  0.71532806],
       [ 2.45882905,  1.55644871],
       [-0.79471015,  0.71532806],
       [-0.79471015,  1.34616854],
       [-0.21372101, -0.33607276],
       [ 0.83205945, -0.1257926 ],
       [-0.44611666,  1.76672887],
       [ 1.41304859,  0.29476773],
       [ 0.01867465, -0.54635292],
       [ 2.22643339, -0.96691325],
       [-0.32991883, -1.17719341],
       [ 0.13487248,  0.29476773],
       [-1.0271058 ,  1.13588838],
       [-1.49189712, -1.59775374],
       [ 0.59966379, -0.54635292],
       [-1.60809495, -0.33607276],
       [-0.91090798,  1.13588838],
       [ 1.64544425, -0.1257926 ],
       [ 0.25107031,  0.71532806],
       [ 0.48346596, -1.8080339 ],
       [ 1.8778399 ,

In [724]:
from sklearn.preprocessing import Normalizer
#scale feature vars with normalizer
scaler = Normalizer().fit(X_train)
normalized_X = scaler.transform(X_train)
normalized_X_test = scaler.transform(X_test)
normalized_X

array([[-0.49528034, -0.86873321],
       [-0.99663389,  0.08198101],
       [ 0.35138344, -0.93623164],
       [ 0.01931008, -0.99981354],
       [ 0.8211053 , -0.57077674],
       [-0.97368976,  0.22787772],
       [-0.88722619,  0.46133468],
       [-0.55952344, -0.82881452],
       [-0.84774384,  0.53040587],
       [ 0.84494482,  0.53485348],
       [-0.74325279,  0.66901068],
       [-0.5083722 ,  0.86113745],
       [-0.53661905, -0.84382462],
       [ 0.98876421, -0.14948357],
       [-0.24482539,  0.96956719],
       [ 0.97892746,  0.20420828],
       [ 0.03416061, -0.99941636],
       [ 0.91723587, -0.39834451],
       [-0.26986101, -0.96289928],
       [ 0.41606981,  0.90933268],
       [-0.67069687,  0.74173156],
       [-0.68247967, -0.73090458],
       [ 0.73920089, -0.673485  ],
       [-0.97885225, -0.2045685 ],
       [-0.62561479,  0.78013212],
       [ 0.99709052, -0.07622659],
       [ 0.33117933,  0.94356783],
       [ 0.25832285, -0.96605864],
       [ 0.96018539,

In [725]:
from sklearn.preprocessing import Binarizer
#binarize feature vars
binarizer = Binarizer(threshold=0.0).fit(X)
binary_X = binarizer.transform(X)
binary_X

array([[0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 0.],
       [1., 0., 1., 0., 0.],
       [1., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 1.],
       [0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1.]])

In [726]:
from sklearn.preprocessing import LabelEncoder
#transform target var with labelencoder
enc = LabelEncoder()
y = enc.fit_transform(y)
y

array([1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0])

In [727]:
import numpy as np
from sklearn.model_selection import train_test_split
#def target and feature vars
X = np.random.random((10,5))
y = np.array(['M','M','F','F','M','F','M','M','F','F'])
X[X<0.7] = 0
#split into train/test
X_train, X_test, y_train, y_test = train_test_split(X,y)

In [728]:
from sklearn.impute import SimpleImputer
#replace missing values 
imp = SimpleImputer(missing_values=0,strategy='mean')
imp.fit_transform(X_train)

array([[0.72299385, 0.79976262, 0.83027015, 0.92146546, 0.81496471],
       [0.72299385, 0.79976262, 0.78683166, 0.92146546, 0.81496471],
       [0.72299385, 0.79976262, 0.74339318, 0.92146546, 0.71017651],
       [0.72299385, 0.79976262, 0.78683166, 0.99931168, 0.96376134],
       [0.72299385, 0.79976262, 0.78683166, 0.92146546, 0.90901626],
       [0.72299385, 0.79976262, 0.78683166, 0.92146546, 0.73841729],
       [0.72299385, 0.79976262, 0.78683166, 0.84361923, 0.75345216]])

In [729]:
from sklearn.preprocessing import PolynomialFeatures
#def polynomial features model
poly = PolynomialFeatures(5)
poly.fit_transform(X)

array([[1.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [1.        , 0.72299385, 0.79976262, ..., 0.        , 0.        ,
        0.62066644],
       [1.        , 0.        , 0.        , ..., 0.30441075, 0.27187495,
        0.24281662],
       ...,
       [1.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [1.        , 0.        , 0.87470282, ..., 0.        , 0.        ,
        0.        ],
       [1.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [730]:
from sklearn.linear_model import LinearRegression
iris = datasets.load_iris()
X, y = iris.data[:,:2], iris.target
#load iris dataset and divide into target and feature vars
X_train, X_test, y_train, y_test = train_test_split(X,y,random_state=33)
#split into test/target
scaler = preprocessing.StandardScaler().fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)
#scale with standardscaler
lr = LinearRegression(fit_intercept = True)
lr.fit(X_train, y_train)
y_pred = lr.predict(X_test)
#fit and predict target vars
y_pred

array([ 0.94143905,  1.51408589,  0.06217379,  1.55899811,  1.40352779,
        1.11332084,  0.00905584,  0.15632042,  1.30549763,  1.59182105,
        1.52229163, -0.0237671 ,  1.05199715,  1.21955674,  1.65314473,
        1.428145  ,  1.08870363,  0.22584984,  1.11332084,  1.80040931,
        0.26255632,  0.38952589,  1.43635074,  0.25435058,  1.57929312,
        1.35040984,  1.15823305,  1.28088042,  1.43635074,  1.01917421,
        0.994557  ,  1.51408589,  0.93323332,  1.24417394,  1.51408589,
        1.57540958,  1.13361585,  0.88011537])

In [731]:
#regression accuracy functions

In [732]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_test,y_pred)

0.43689429711441596

In [733]:
from sklearn.metrics import mean_squared_error
mean_squared_error(y_test,y_pred)

0.27772586541100364

In [734]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.5568661329795699

In [735]:
#load iris dataset
iris = datasets.load_iris()
#def target and feature vars
X, y = iris.data, iris.target
#test and train vars
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.33)

In [736]:
from sklearn.svm import SVC
svc = SVC(kernel='linear')
#define svc model
svc.fit(X_train, y_train)
y_pred = svc.predict(X_test)
#fit and predict target vars
y_pred

array([2, 1, 0, 1, 1, 0, 0, 1, 0, 2, 2, 2, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1,
       0, 0, 1, 2, 2, 2, 2, 2, 2, 0, 1, 2, 0, 2, 2, 1, 1, 0, 0, 0, 2, 1,
       2, 2, 0, 1, 2, 2])

In [737]:
#classification accuracy functions

In [738]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.98

In [739]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       0.94      1.00      0.97        15
           2       1.00      0.95      0.97        19

    accuracy                           0.98        50
   macro avg       0.98      0.98      0.98        50
weighted avg       0.98      0.98      0.98        50



In [740]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test,y_pred))

[[16  0  0]
 [ 0 15  0]
 [ 0  1 18]]


In [741]:
from sklearn.naive_bayes import GaussianNB
#import and define naive bayes model
gnb = GaussianNB()
gnb.fit(X_train, y_train)
y_pred = gnb.predict(X_test)
#fit and predict target vars
y_pred

array([2, 1, 0, 1, 1, 0, 0, 1, 0, 2, 2, 2, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1,
       0, 0, 1, 2, 2, 2, 2, 2, 2, 0, 1, 2, 0, 2, 2, 1, 1, 0, 0, 0, 2, 1,
       2, 2, 0, 1, 2, 2])

In [742]:
from sklearn import neighbors
knn = neighbors.KNeighborsClassifier(n_neighbors=5)
#import and def kn model
knn.fit(X_train, y_train)
y_pred = knn.predict_proba(X_test)
#fit and predict probabilities for input
knn.score(X_test, y_test)
#score accuracy of given model

1.0

In [743]:
from sklearn.decomposition import PCA
#import and def PCA model
pca = PCA(n_components=0.95)
pca_model = pca.fit_transform(X_train)
#fit features
pca_model

array([[-2.71949523, -0.11442134],
       [ 2.99979224,  0.88584137],
       [-2.51694496, -0.00703228],
       [-2.7891462 , -0.17223991],
       [ 0.23659214, -0.27544181],
       [-2.52563272,  1.0720063 ],
       [ 1.35903816, -0.1146686 ],
       [-2.31609315,  1.32269396],
       [-2.64232378, -0.3428167 ],
       [ 2.70247206,  0.43753897],
       [ 1.40769192, -0.69801222],
       [ 2.51465268,  0.39809258],
       [ 1.17832426,  0.13384115],
       [ 0.64873351, -1.14252881],
       [ 1.31414267, -0.54038604],
       [ 1.6450262 ,  0.33754463],
       [-2.55158872,  0.28955525],
       [-2.57022023,  0.790538  ],
       [-2.12092495,  0.42452441],
       [-0.63136728, -0.98497363],
       [-2.22602744,  0.37520344],
       [-2.53972541, -0.14386814],
       [ 1.54354357,  0.57093514],
       [-2.7772829 , -0.6056633 ],
       [ 0.73440277,  0.06697351],
       [-2.45266778,  0.48366752],
       [ 1.88060471, -0.42783369],
       [-0.20549064, -0.3398913 ],
       [ 0.98507562,

In [744]:
from sklearn.cluster import KMeans
#import and define kmeans model
k_means = KMeans(n_clusters=3,random_state=0)
k_means.fit(X_train)
#fit and predict target vars
y_pred = k_means.predict(X_test)
y_pred

array([2, 2, 1, 2, 2, 1, 1, 0, 1, 0, 0, 0, 2, 1, 1, 2, 2, 1, 2, 2, 1, 2,
       1, 1, 2, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 2, 2, 1, 1, 1, 0, 2,
       0, 0, 1, 2, 0, 2], dtype=int32)

In [745]:
#clustering accuracy functions

In [746]:
from sklearn.metrics import adjusted_rand_score
adjusted_rand_score(y_test,y_pred)

0.8261401042930461

In [747]:
from sklearn.metrics import homogeneity_score
homogeneity_score(y_test,y_pred)

0.8191046543918387

In [748]:
from sklearn.metrics import v_measure_score
v_measure_score(y_test,y_pred)

0.8177810710732283

In [749]:
#model cross validation
from sklearn.model_selection  import cross_val_score
cross_val_score(svc, X_train, y_train, cv=4)

array([0.92, 0.96, 0.96, 0.92])

In [750]:
#load iris dataset
iris = datasets.load_iris()
#def target and feature vars
X, y = iris.data, iris.target
#test and train vars
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.33)

In [751]:
#determine optimal model hyperparameters - gridsearch
from sklearn.model_selection import GridSearchCV
knn = neighbors.KNeighborsClassifier()
params = {'n_neighbors':np.arange(1,3),'metric':['euclidean','cityblock']}
grid = GridSearchCV(knn,params)
grid.fit(X_train, y_train)
print(grid.best_score_)
print(grid.best_estimator_.n_neighbors)

0.96
1


In [752]:
#determine optimal model hyperparameters - randomizedsearch
from sklearn.model_selection import RandomizedSearchCV
params = {'n_neighbors':range(1,5),'weights':['uniform','distance']}
rsearch = RandomizedSearchCV(estimator=knn, param_distributions=params,cv=4,n_iter=8)
rsearch.fit(X_train,y_train)
print(rsearch.best_score_)

0.97
