In [47]:

from sklearn import datasets,preprocessing
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
import numpy as np
iris = datasets.load_iris()
#load iris dataset
X, y = iris.data[:,:2], iris.target
#def target and feature vars
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.33)
#test and train vars
scaler = preprocessing.StandardScaler().fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)
#scale feature vars
lr = LinearRegression(fit_intercept = True)
#def linear regression model
lr.fit(X_train, y_train)
y_pred = lr.predict(X_test)
#fit and predict target vars
r2_score(y_test,y_pred)
#score accuracy


0.7867717664972643

In [48]:
from sklearn import datasets,preprocessing
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.preprocessing import Normalizer
import numpy as np
#load iris dataset
iris = datasets.load_iris()
#def target and feature vars
X, y = iris.data[:,:2], iris.target
#test and train vars
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.33)
scaler = Normalizer().fit(X_train)
#different feature var scaler
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)
#scale feature vars
lr = LinearRegression(fit_intercept = True)
#def linear regression model
lr.fit(X_train, y_train)
y_pred = lr.predict(X_test)
#fit, predict and score accuracy
r2_score(y_test,y_pred)

0.651264028501221

In [41]:
from sklearn import datasets,preprocessing
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
import numpy as np
#load iris dataset
iris = datasets.load_iris()
#def target and feature vars
X, y = iris.data, iris.target
#test and train vars
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.33)
scaler = preprocessing.StandardScaler().fit(X_train)
#scale feature vars
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)
#def naive bayes model
gnb = GaussianNB()
gnb.fit(X_train,y_train)
y_pred = gnb.predict(X_test)
#fit, predict and score accuracy
accuracy_score(y_pred,y_test)

1.0

In [54]:
from sklearn import datasets,preprocessing
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import Normalizer
import numpy as np
#load iris dataset
iris = datasets.load_iris()
#def target and feature vars
X, y = iris.data, iris.target
#test and train vars
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.33)
scaler = Normalizer().fit(X_train)
#scale feature vars
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)
#def naive bayes model
gnb = GaussianNB()
gnb.fit(X_train,y_train)
y_pred = gnb.predict(X_test)
#fit ,predict and score accuracy via confusion matrix
confusion_matrix(y_pred,y_test)

array([[11,  0,  0],
       [ 0, 15,  1],
       [ 0,  2, 21]])

In [61]:
import numpy as np
from sklearn import datasets,preprocessing
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix
iris = datasets.load_iris()
#load iris dataset
X, y = iris.data, iris.target
#def target and feature vars
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.33)
#test and train vars
scaler = preprocessing.StandardScaler().fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)
#scale feature vars
clf = SVC()
#def svc model
clf.set_params(kernel = 'linear').fit(X_train, y_train)
y_pred = clf.predict(X_test)
#set different parameters and refit
clf.set_params(kernel = 'rbf', gamma = 'scale').fit(X_train, y_train)
y_pred = clf.predict(X_test)
#predict and score accuracy via confusion matrix
confusion_matrix(y_pred,y_test)

array([[18,  0,  0],
       [ 0, 15,  0],
       [ 0,  3, 14]])

In [59]:
import numpy as np
from sklearn import datasets,preprocessing
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import Normalizer
iris = datasets.load_iris()
#load iris dataset
X, y = iris.data, iris.target
#def target and feature vars
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.33)
#test and train vars
scaler = Normalizer().fit(X_train)
#scale feature vars
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)
#def svc model
clf = SVC()
clf.set_params(kernel = 'linear').fit(X_train, y_train)
y_pred = clf.predict(X_test)
#refit with different params
#clf.set_params(kernel = 'rbf', gamma = 'scale').fit(X_train, y_train)
#y_pred = clf.predict(X_test)
#predict and score accuracy via confusion matrix
confusion_matrix(y_pred,y_test)

array([[18,  0,  0],
       [ 0, 11, 21],
       [ 0,  0,  0]])

In [53]:
from sklearn import datasets,preprocessing
from sklearn.model_selection import train_test_split
from sklearn import neighbors
from sklearn.metrics import confusion_matrix
import numpy as np
#load iris dataset
iris = datasets.load_iris()
#def target and feature vars
X, y = iris.data, iris.target
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.33)
#test and train vars
scaler = preprocessing.StandardScaler().fit(X_train)
#scale feature vars
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)
#def kneighbors model
knn = neighbors.KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train,y_train)
y_pred = knn.predict(X_test)
#fit, predict and score accuracy via confusion matrix
confusion_matrix(y_pred,y_test)

array([[18,  0,  0],
       [ 0, 12,  1],
       [ 0,  0, 19]])

In [46]:
from sklearn import datasets,preprocessing
from sklearn.model_selection import train_test_split
from sklearn import neighbors
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import Normalizer
import numpy as np
#load iris dataset
iris = datasets.load_iris()
#def target and feature vars
X, y = iris.data, iris.target
#test and train vars
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.33)
scaler = Normalizer().fit(X_train)
#scale feature vars
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)
#def kneighbors model
knn = neighbors.KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train,y_train)
y_pred = knn.predict(X_test)
#fit, predict and score accuracy
accuracy_score(y_pred,y_test)

0.98

In [94]:
from sklearn import datasets,preprocessing
from sklearn.model_selection import train_test_split,GridSearchCV
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix,accuracy_score
from sklearn.preprocessing import Normalizer
import numpy as np
#load iris dataset
iris = datasets.load_iris()
#def target and feature vars
X, y = iris.data, iris.target
#test and train vars
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.8)
scaler = Normalizer().fit(X_train)
#scale feature vars
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)
#def svc model and hyperparameters
parameters = {'kernel':('linear', 'rbf'), 'C':[1, 10]}
svc = SVC()
clf = GridSearchCV(svc, parameters)
#find optimal hyperparameters by gridsearch
clf.fit(X_train,y_train)
y_pred = clf.predict(X_test)
#fit, predict and score accuracy
confusion_matrix(y_pred,y_test)
accuracy_score(y_pred,y_test)

0.9666666666666667

In [104]:

from sklearn import datasets,preprocessing
from sklearn.model_selection import train_test_split,RandomizedSearchCV
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix,accuracy_score
from sklearn.preprocessing import Normalizer
import numpy as np
#load iris dataset
iris = datasets.load_iris()
#def target and feature vars
X, y = iris.data, iris.target
#test and train vars
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.8)
scaler = Normalizer().fit(X_train)
#scale feature vars
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)
#def svc model and parameters
parameters = {'kernel':('linear', 'rbf'), 'C':[1, 10]}
svc = SVC()
#find optimal parameters via randomized search
clf = RandomizedSearchCV(svc, parameters,n_iter=4)
clf.fit(X_train,y_train)
y_pred = clf.predict(X_test)
#fit, predict and score accuracy
confusion_matrix(y_pred,y_test)
accuracy_score(y_pred,y_test)


0.95

In [109]:
from sklearn import datasets,preprocessing
from sklearn.model_selection import train_test_split,GridSearchCV
from sklearn.metrics import confusion_matrix,accuracy_score
from sklearn import neighbors
import numpy as np
#load iris dataset
iris = datasets.load_iris()
#def target and feature vars
X, y = iris.data, iris.target
#test and train vars
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.33)
scaler = preprocessing.StandardScaler().fit(X_train)
#scale feature vars
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)
#def kn model and parameters
knn = neighbors.KNeighborsClassifier()
params = {'n_neighbors':np.arange(1,3),'metric':['euclidean','cityblock']}
#define hyperparameter format and find optimal values via gridsearch
kngs = GridSearchCV(knn,params)
kngs.fit(X_train,y_train)
y_pred = kngs.predict(X_test)
#fit, predict and score accuracy
confusion_matrix(y_pred,y_test)
accuracy_score(y_pred,y_test)

0.92

In [115]:
from sklearn import datasets,preprocessing
from sklearn.model_selection import train_test_split,RandomizedSearchCV
from sklearn.metrics import confusion_matrix,accuracy_score
from sklearn import neighbors
import numpy as np
#load iris dataset
iris = datasets.load_iris()
#def target and feature vars
X, y = iris.data, iris.target
#test and train vars
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.33)
scaler = preprocessing.StandardScaler().fit(X_train)
#scale feature vars
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)
#def kn model and parameters
knn = neighbors.KNeighborsClassifier()
params = {'n_neighbors':np.arange(1,3),'metric':['euclidean','cityblock']}
#define hyperparameters and find optimal values via gridsearch
kngs = GridSearchCV(knn,params)
kngs.fit(X_train,y_train)
y_pred = kngs.predict(X_test)
#fit, predict and score accuracy
confusion_matrix(y_pred,y_test)
accuracy_score(y_pred,y_test)
#get gridsearch hyperparameters
kngs.get_params()

{'cv': None,
 'error_score': nan,
 'estimator__algorithm': 'auto',
 'estimator__leaf_size': 30,
 'estimator__metric': 'minkowski',
 'estimator__metric_params': None,
 'estimator__n_jobs': None,
 'estimator__n_neighbors': 5,
 'estimator__p': 2,
 'estimator__weights': 'uniform',
 'estimator': KNeighborsClassifier(),
 'n_jobs': None,
 'param_grid': {'n_neighbors': array([1, 2]),
  'metric': ['euclidean', 'cityblock']},
 'pre_dispatch': '2*n_jobs',
 'refit': True,
 'return_train_score': False,
 'scoring': None,
 'verbose': 0}